import Head from 'next/head'
import styles from '../styles/Home.module.css'
import utils from '../styles/utils.module.css'

import Searchbar from '../components/searchbar/searchbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/devchallenges.png" />
      </Head>

      <header className={styles.header}>
        <Searchbar />
        <button className={utils.btn + " " + utils.btnWithBackground + " " + utils.btnGreen}>
          Add a photo
        </button>
      </header>

      <main className={styles.main}>
        
      </main>
    </div>
  )
}
